[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
# Nếu bạn dùng Arduino Nano đời mới (New Bootloader), hãy giữ nguyên. 
# Nếu nạp code lỗi, hãy thử đổi board thành: nanoatmega328new
monitor_speed = 115200
lib_deps =
    Servo
    4-20ma/ModbusMaster @ ^2.0.1
    featherfly/SoftwareSerial @ ^1.0    